### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by rugk** [Gaff/pgp.help#32]
There are no installation instruction s at all.
So how can I install this?

I tried this:
```console
$ npm install
$ gulp
```

But I still don't know where my static files are saved? There is no `build` dir or something similar...

**Comment by Gaff** [comment]
Easiest way to grok installation is to inspect the travis yaml / output. Try looking here:

https://travis-ci.org/Gaff/pgp.help/jobs/129263806
https://github.com/Gaff/pgp.help/blob/master/.travis.yml

Having said that I've exclusively operated this site from github pages, I'm not entirely sure how to install it myself :)

**Comment by rugk** [comment]
Yes, thanks.

So I tried to build it with `gulp` now and the new version fails with this error:
```console
$ gulp
No browserSync
{ [Error: Cannot find module 'browser-sync'] code: 'MODULE_NOT_FOUND' }
[22:15:53] Using gulpfile /.../gulpfile.js
[22:15:53] Starting 'clean'...
[22:15:53] Finished 'clean' after 84 ms
[22:15:53] Starting 'default'...
[22:15:53] Starting 'build'...
[22:15:53] Starting 'bower'...
[22:15:55] Using cwd:  /...
[22:15:56] Using bower dir:  ./bower_components
[22:15:58] Finished 'default' after 5.36 s
[22:15:59] Finished 'build' after 5.63 s
[22:16:00] bower cached https://github.com/angular-ui/bootstrap-bower.git#1.3.3
[22:16:00] bower validate 1.3.3 against https://github.com/angular-ui/bootstrap-bower.git#~1.3.3
[22:16:00] bower cached https://github.com/angular/bower-angular.git#1.5.6
[22:16:00] bower validate 1.5.6 against https://github.com/angular/bower-angular.git#>=1.3.0
[22:16:00] bower cached https://github.com/angular-ui/angular-ui-router-bower.git#0.3.0
[22:16:00] bower validate 0.3.0 against https://github.com/angular-ui/angular-ui-router-bower.git#~0.3.0
[22:16:00] bower cached https://github.com/angular/bower-angular.git#1.5.6
[22:16:00] bower validate 1.5.6 against https://github.com/angular/bower-angular.git#^1.0.8
[22:16:00] bower cached https://github.com/angular/bower-angular.git#1.5.6
[22:16:00] bower validate 1.5.6 against https://github.com/angular/bower-angular.git#~1.5.6
[22:16:00] bower cached https://github.com/openpgpjs/openpgpjs.git#1.5.7
[22:16:00] bower validate 1.5.7 against https://github.com/openpgpjs/openpgpjs.git#~1.5.7
[22:16:00] bower cached https://github.com/angular/bower-angular-animate.git#1.5.6
[22:16:00] bower validate 1.5.6 against https://github.com/angular/bower-angular-animate.git#~1.5.6
[22:16:00] bower cached https://github.com/angular/bower-angular.git#1.4.11
[22:16:00] bower validate 1.4.11 against https://github.com/angular/bower-angular.git#1.4.11

/.../node_modules/bower/lib/node_modules/q/q.js:155
                throw e;
                ^
angular: Unable to find suitable version for angular
    at createError (/.../node_modules/bower/lib/util/createError.js:4:15)
    at Manager._electSuitable (/.../node_modules/bower/lib/core/Manager.js:823:15)
    at /.../node_modules/bower/lib/core/Manager.js:609:25
    at _fulfilled (/.../node_modules/bower/lib/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/.../node_modules/bower/lib/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/.../node_modules/bower/lib/node_modules/q/q.js:796:13)
    at /.../node_modules/bower/lib/node_modules/q/q.js:556:49
    at runSingle (/.../node_modules/bower/lib/node_modules/q/q.js:137:13)
    at flush (/.../node_modules/bower/lib/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

So possibly the wrong angular version?

So I installed it manually via `bower install` and get this question:
```
Unable to find a suitable version for angular, please choose one by typing one of the numbers below:
    1) angular#1.4.11 which resolved to 1.4.11 and is required by angular-animate#1.4.11
    2) angular#^1.0.8 which resolved to 1.5.6 and is required by angular-ui-router#0.3.0
    3) angular#~1.5.6 which resolved to 1.5.6 and is required by pgp.help
    4) angular#>=1.3.0 which resolved to 1.5.6 and is required by angular-bootstrap#0.13.4
    5) angular#>=1.4.0 which resolved to 1.5.6 and is required by angular-bootstrap#1.3.3
    6) angular#1.5.6 which resolved to 1.5.6 and is required by angular-animate#1.5.6
```

This really seem to be some dependency issues. I selected 3 for now.
And this is working...
